[package]
name = "poc"
edition = "2024.beta" # Use 2024.beta or 2024
published-at = "0x082fed1939954aa12b1e6a36ee7648e6fee57349f630c0494a4899d1ae2af794"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
poc = "0x082fed1939954aa12b1e6a36ee7648e6fee57349f630c0494a4899d1ae2af794"
